# Generated by Django 4.2.3 on 2025-05-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
