# Generated by Django 4.2.3 on 2025-05-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='details',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='passing_year',
        ),
        migrations.AddField(
            model_name='details',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='cgpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
