# Generated by Django 4.2.3 on 2025-05-25 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('details', '0002_remove_details_certification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cgpa', models.FloatField()),
                ('logical_quotient_rating', models.IntegerField()),
                ('hackathons', models.IntegerField()),
                ('coding_skills_rating', models.IntegerField()),
                ('public_speaking_points', models.IntegerField()),
                ('can_work_long_time_before_system', models.CharField(max_length=50)),
                ('self_learning_capability', models.CharField(max_length=50)),
                ('certifications', models.TextField()),
                ('reading_and_writing_skills', models.CharField(max_length=100)),
                ('memory_capability_score', models.CharField(max_length=50)),
                ('interested_subjects', models.TextField()),
                ('interested_career_area', models.CharField(max_length=100)),
                ('job_or_higher_studies', models.CharField(max_length=50)),
                ('type_of_company_want_to_settle', models.CharField(max_length=100)),
                ('interested_in_games', models.CharField(max_length=50)),
                ('interested_type_of_books', models.CharField(max_length=100)),
                ('salary_range_expected', models.CharField(max_length=50)),
                ('gentle_or_tuff_behaviour', models.CharField(max_length=50)),
                ('management_or_technical', models.CharField(max_length=50)),
                ('worked_in_teams_ever', models.CharField(max_length=50)),
                ('introvert', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
